# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Scrap Paper'
tagline:          'Blog'
description:      'Cloud Computing & Machine Learning.'
url:              http://horaceheaven.com
baseurl:          /

author:
  name:           'Horace Heaven'
  url:            https://twitter.com/horaceheaven

paginate:         5

# Custom vars
version:          2.1.0

twitter:
  url:          https://twitter.com/horaceheaven.com
linkedin:
  url:          https://www.linkedin.com/in/horaceheaven/
github:
  url:           https://github.com/horaceheaven
